### ISSUE TITLE
Longitudinal issue

### ISSUE THREAD

**Issue by AntoineThiboult** [KW-M/sl2-csv-converter#6]
It seems that Lowrance handles positive and negative longitudinal coordinatates in a different way. You can find a note on this subject written by [Chris78](https://github.com/Chris78) [here](https://github.com/Chris78/sl2decode). His ruby code works as expected.

**Comment by KW-M** [comment]
Thanks so much for this tip. I updated it based on Chris78's code and it is fixed!
